using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace Week6ConsoleApp.CircusServices
{
    internal class NamingService
    {
        Random random = new Random();

        /// <summary>
        /// Names generated by chatGPT
        /// </summary>
        string[] names = {
            "Ringo",
            "Tango",
            "Bubbles",
            "Jumbo",
            "Sparky",
            "Ziggy",
            "Gigi",
            "Sassy",
            "Pogo",
            "Lucky",
            "Hank",
            "Dumbo",
            "Charlie",
            "Kiki",
            "Milo"
        };

        public string GetRandomName()
        {
            return names[random.Next(names.Length)];
        }

    }
}
